### ISSUE TITLE
新增操作后一直显示加载中，且保存失败

### ISSUE THREAD

**Issue by janecms** [MuxinFeng/taro-savePassword#2]
![1636940787541](https://user-images.githubusercontent.com/3897037/141709654-cbb4cc11-0994-4762-afdb-4936225cdb5e.jpg)

麻烦看一下问题

**Comment by MuxinFeng** [comment]
目前这个问题在我这边的设备上无法复现，我会再找几台设备看一下的，尽量在今明两天给你一个回复

**Comment by MuxinFeng** [comment]
经过测试，排查出是部分账号连接云数据库的时候（获取不到openid）出了问题，跟设备无关；最近我手头要进行的事比较多，你可以试着自己解决一下
